<?php
// Auto-generated by ABCD Central API Manager
define('IS_WINDOWS', strtoupper(substr(PHP_OS, 0, 3)) === 'WIN');

return [
    'api_root_path' => 'C:/xampp/htdocs/ABCD2/www/htdocs/abcd-api',
    'wxis_host' => '127.0.0.1:9000',
    'cisis_path' => [
        'windows' => '/cgi-bin/',
        'linux'   => '/cgi-bin/'
    ],
    'exe_extension' => IS_WINDOWS ? '.exe' : '',
];
