<?php
// Auto-generated by ABCD Central API Manager
return array (
  'marc' => 
  array (
    'name' => 'MARC',
    'description' => 'Base de dados de exemplo em formato MARC.',
    'access' => 'public',
    'database_path' => '\\xampp\\htdocs\\ABCD\\www\\bases-examples_Windows\\marc\\data\\marc',
    'mapping' => 'marc.i2x',
    'cisis_version' => 'ansi/',
    'source_encoding' => 'ISO-8859-1',
  ),
  'spectrum' => 
  array (
    'name' => 'SPECTRUM',
    'description' => 'SPECTRUM - Museum Management Standard',
    'access' => 'restricted',
    'database_path' => '\\xampp\\htdocs\\ABCD\\www\\bases-examples_Windows\\spectrum\\data\\spectrum',
    'mapping' => 'spectrum.i2x',
    'cisis_version' => 'ansi/',
    'source_encoding' => 'ISO-8859-1',
  ),
  'dubcore' => 
  array (
    'name' => 'DUBCORE',
    'description' => 'Base de dados de exemplo em formato Dublin Core.',
    'access' => 'restricted',
    'database_path' => '\\xampp\\htdocs\\ABCD\\www\\bases-examples_Windows\\dubcore\\data\\dubcore',
    'mapping' => 'dubcore.i2x',
    'cisis_version' => 'utf8/',
    'source_encoding' => 'UTF-8',
  ),
);
