<?php
// Auto-generated by ABCD Central API Manager
return array (
  'marc' => 
  array (
    'author' => 'AU_',
    'title' => 'TT_',
    'subject' => 'MA_',
    'words' => 'TW_',
  ),
  'dubcore' => 
  array (
    'title' => 'TI_',
    'creator' => 'AU_',
    'words' => 'TW_',
  ),
);
