<?php

/**
 * Name: api_manager.php
 * Author: Roger C. Guilherme
 * Created: 2026-08-10
 * Description: ABCD REST API Manager
 * This file handles the configuration of the REST API, including general settings,
 * API Key management, Database Exposure, and Search Mappings.
 * 
 * @package ABCD_Core_Settings
 * @requires PHP 8.1+
 */

session_start();
if (!isset($_SESSION["permiso"])) {
    header("Location: ../common/error_page.php");
    exit;
}

require_once("../config.php");
require_once("../common/get_post.php");

$lang = $_SESSION["lang"] ?? "en";
@include("../lang/admin.php");

// 1. Define API Paths
$apiRootPath = realpath(dirname(__DIR__, 2) . '/abcd-api');
$appConfigFile = $apiRootPath . '/config/app.php';
$registryFile = $apiRootPath . '/config/api_keys.json';
$searchConfigFile = $apiRootPath . '/config/search_config.php';
$databasesConfigFile = $apiRootPath . '/config/databases.php';

$message = '';
$messageType = '';
$newlyGeneratedKey = '';

// --- HELPER FUNCTION: Compile auth.php ---
function compileAuthCache($registry, $apiRootPath)
{
    $authFile = $apiRootPath . '/config/auth.php';
    $activeKeys = [];
    foreach ($registry as $hash => $data) {
        if (($data['status'] ?? '') === 'active') {
            $activeKeys[$hash] = [
                'description' => $data['client_name'],
                'scope' => $data['scope']
            ];
        }
    }
    $content = "<?php\n// Auto-generated Auth Cache by ABCD Central\nreturn [\n    'keys' => " . var_export($activeKeys, true) . "\n];\n";
    file_put_contents($authFile, $content);
}

// --- HELPER FUNCTION: Detect CISIS Version from dr_path.def ---
function detectCisisEnvironment($dbPath, $dbCode)
{
    $drPathFile = rtrim($dbPath, '/\\') . '/' . $dbCode . '/dr_path.def';

    // Default ABCD fallback values (as seen in wxis_llamar.php)
    $unicode = 'ansi';
    $charset = 'ISO-8859-1';
    $cisis_ver = '';

    if (file_exists($drPathFile)) {
        $def_db = parse_ini_file($drPathFile);

        // Check CISIS_VERSION (Ignoring legacy "16-60")
        if (isset($def_db["CISIS_VERSION"]) && $def_db["CISIS_VERSION"] !== "16-60") {
            $cisis_ver = trim($def_db["CISIS_VERSION"]);
        }

        // Check UNICODE
        if (isset($def_db["UNICODE"]) && $def_db["UNICODE"] !== "ansi" && $def_db["UNICODE"] !== '0') {
            $unicode = 'utf8';
            $charset = 'UTF-8';
        }
    }

    if ($cisis_ver !== "") {
        $cisis_ver .= "/";
    }

    return [
        'cisis_version' => $unicode . '/' . $cisis_ver,
        'source_encoding' => $charset
    ];
}

// 2. Handle POST Actions
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {

    // Action: Save General Settings
    if ($_POST['action'] === 'save_general') {
        $wxisHost = addslashes(trim($_POST['wxis_host'] ?? '127.0.0.1'));
        $systemPath = addslashes(trim($_POST['api_root_path'] ?? 'C:/xampp/htdocs/ABCD2/www/htdocs/abcd-api'));

        $configContent = "<?php\n"
            . "// Auto-generated by ABCD Central API Manager\n"
            . "if (!defined('IS_WINDOWS')) {\n"
            . "    define('IS_WINDOWS', strtoupper(substr(PHP_OS, 0, 3)) === 'WIN');\n"
            . "}\n\n"
            . "return [\n"
            . "    'api_root_path' => '{$systemPath}',\n"
            . "    'wxis_host' => '{$wxisHost}',\n"
            . "    'cisis_path' => [\n"
            . "        'windows' => '/cgi-bin/',\n"
            . "        'linux'   => '/cgi-bin/'\n"
            . "    ],\n"
            . "    'exe_extension' => IS_WINDOWS ? '.exe' : '',\n"
            . "];\n";

        if (file_put_contents($appConfigFile, $configContent) !== false) {
            $message = $msgstr['api_settings_updated'] ?? "API settings updated successfully.";
            $messageType = "success";
        }
    }

    // Action: Generate New Key
    if ($_POST['action'] === 'generate_key') {
        $clientName = trim($_POST['client_name'] ?? 'Unknown Client');
        $scope = $_POST['scope'] ?? 'read';

        $plainTextKey = 'abcd_sk_' . bin2hex(random_bytes(16));
        $hashedKey = hash('sha256', $plainTextKey);

        $registry = file_exists($registryFile) ? json_decode(file_get_contents($registryFile), true) : [];
        $registry[$hashedKey] = [
            'client_name' => $clientName,
            'scope' => $scope,
            'created_at' => date('Y-m-d H:i:s'),
            'status' => 'active'
        ];

        if (file_put_contents($registryFile, json_encode($registry, JSON_PRETTY_PRINT))) {
            compileAuthCache($registry, $apiRootPath);
            $newlyGeneratedKey = $plainTextKey;
            $message = $msgstr['api_key_generated'] ?? "Key generated successfully!";
            $messageType = "success";
        } else {
            $message = $msgstr['api_key_gen_error'] ?? "Error saving the new key.";
            $messageType = "error";
        }
    }

    // Action: Delete / Revoke Key
    if ($_POST['action'] === 'delete_key') {
        $keyHash = $_POST['key_hash'] ?? '';
        $registry = file_exists($registryFile) ? json_decode(file_get_contents($registryFile), true) : [];

        if (isset($registry[$keyHash])) {
            unset($registry[$keyHash]);

            if (file_put_contents($registryFile, json_encode($registry, JSON_PRETTY_PRINT))) {
                compileAuthCache($registry, $apiRootPath);
                $message = $msgstr['api_key_revoked'] ?? "API key successfully revoked and deleted.";
                $messageType = "success";
            } else {
                $message = $msgstr['api_key_revoke_error'] ?? "Error updating the key registry file.";
                $messageType = "error";
            }
        }
    }

    // Action: Save Databases & Search Config Unified
    if ($_POST['action'] === 'save_db_config') {
        $enabledBases = $_POST['enable_db'] ?? [];
        $accessLevels = $_POST['access_level'] ?? [];
        $descriptions = $_POST['db_desc'] ?? [];
        $mappings = $_POST['mapping'] ?? [];

        $exportDatabases = [];
        $exportSearch = [];

        foreach ($enabledBases as $dbKey) {
            // Build Database Config
            $exportDatabases[$dbKey] = [
                'name' => strtoupper($dbKey),
                'description' => addslashes(trim($descriptions[$dbKey] ?? '')),
                'access' => $accessLevels[$dbKey] ?? 'restricted',
                'database_path' => (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN')
                    ? str_replace('/', '\\', $db_path . $dbKey . '/data/' . $dbKey)
                    : $db_path . $dbKey . '/data/' . $dbKey,
                'mapping' => $dbKey . '.i2x',
                // Now receiving values directly from the form
                'cisis_version' => $_POST['cisis_version'][$dbKey] ?? 'ansi/',
                'source_encoding' => $_POST['source_encoding'][$dbKey] ?? 'ISO-8859-1'
            ];

            // Build Search Mappings for this active DB
            if (isset($mappings[$dbKey]['api_param'])) {
                foreach ($mappings[$dbKey]['api_param'] as $index => $param) {
                    $param = trim($param);
                    $prefix = trim($mappings[$dbKey]['cisis_prefix'][$index] ?? '');
                    if ($param !== '' && $prefix !== '') {
                        $exportSearch[$dbKey][$param] = $prefix;
                    }
                }
            }
        }

        $dbContent = "<?php\n// Auto-generated by ABCD Central API Manager\nreturn " . var_export($exportDatabases, true) . ";\n";
        $searchContent = "<?php\n// Auto-generated by ABCD Central API Manager\nreturn " . var_export($exportSearch, true) . ";\n";

        $dbSaved = file_put_contents($databasesConfigFile, $dbContent);
        $searchSaved = file_put_contents($searchConfigFile, $searchContent);

        if ($dbSaved !== false && $searchSaved !== false) {
            $message = $msgstr['api_db_settings_updated'] ?? "Database settings and mappings updated successfully.";
            $messageType = "success";
        } else {
            $message = $msgstr['api_db_settings_error'] ?? "Error writing configuration files.";
            $messageType = "error";
        }
    }
}

// 3. Load Configurations
$currentConfig = file_exists($appConfigFile) ? require $appConfigFile : [];
$registry = file_exists($registryFile) ? json_decode(file_get_contents($registryFile), true) : [];
$searchConfig = file_exists($searchConfigFile) ? require $searchConfigFile : [];
$databasesConfig = file_exists($databasesConfigFile) ? require $databasesConfigFile : [];

include("../common/header.php");
?>

<body>
    <!-- Internal CSS for Accordions and Grid -->
    <style>
        .abcd-accordion-item {
            border: 1px solid #ddd;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        .abcd-accordion-header {
            background-color: #f1f1f1;
            padding: 10px 15px;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-radius: 5px;
        }

        .abcd-accordion-header:hover {
            background-color: #e2e2e2;
        }

        .abcd-accordion-content {
            display: none;
            padding: 15px;
            background: #fff;
            border-top: 1px solid #ddd;
        }

        .abcd-accordion-item.open .abcd-accordion-content {
            display: block;
        }

        .has-checked .abcd-accordion-header {
            border-left: 5px solid #27ae60;
        }

        .mapping-table th {
            background: #f8f9fa;
        }
    </style>

    <?php include("../common/institutional_info.php"); ?>

    <div class="sectionInfo">
        <div class="breadcrumb">
            <?php echo $msgstr["configure"] ?? 'Configure ABCD'; ?> / <?php echo $msgstr["api_manager"] ?? 'API REST Manager'; ?>
        </div>
        <div class="actions">
            <a href="conf_abcd.php" class="defaultButton backButton">
                <i class="fas fa-arrow-left"></i> <?php echo $msgstr['plugin_back'] ?? 'Back'; ?>
            </a>
        </div>
        <div class="spacer">&#160;</div>
    </div>

    <div class="middle form">
        <div class="formContent">
            <h3><i class="fas fa-network-wired"></i> <?php echo $msgstr["api_config"] ?? 'API REST Configuration'; ?></h3>

            <?php if (!empty($message)): ?>
                <div style="background-color: <?php echo $messageType === 'success' ? '#d4edda' : '#f8d7da'; ?>; 
                            color: <?php echo $messageType === 'success' ? '#155724' : '#721c24'; ?>; 
                            padding: 10px; margin-bottom: 15px; border-radius: 4px;">
                    <strong><?php echo ucfirst($messageType); ?>:</strong> <?php echo htmlspecialchars($message); ?>
                </div>
            <?php endif; ?>

            <?php if (!empty($newlyGeneratedKey)): ?>
                <div style="background-color: #fff3cd; color: #856404; padding: 15px; border: 1px solid #ffeeba; margin-bottom: 20px; border-radius: 5px;">
                    <h4 style="margin-top: 0; color: #856404;"><i class="fas fa-exclamation-triangle"></i> <?php echo $msgstr['api_copy_key_warning'] ?? 'Important! Copy your API Key now'; ?></h4>
                    <p><?php echo $msgstr['api_copy_key_desc'] ?? 'For security reasons, this key will <strong>never be shown again</strong>.'; ?></p>
                    <code style="display: block; background: #fff; padding: 10px; font-size: 1.2em; border: 1px dashed #856404; text-align: center; margin-top: 10px;">
                        <?php echo htmlspecialchars($newlyGeneratedKey); ?>
                    </code>
                </div>
            <?php endif; ?>

            <!-- GENERAL SETTINGS TAB -->
            <fieldset style="border: 1px solid #ccc; padding: 15px; margin-bottom: 20px; border-radius: 5px;">
                <legend style="font-weight: bold; padding: 0 5px;"><?php echo $msgstr['api_general_settings'] ?? 'General Settings'; ?></legend>
                <form method="POST">
                    <input type="hidden" name="action" value="save_general">
                    <div style="margin-bottom: 15px;">
                        <label style="display: block; font-weight: bold;"><?php echo $msgstr['api_wxis_host'] ?? 'WXIS Host Address (w/ Port)'; ?></label>
                        <input type="text" name="wxis_host" value="<?php echo htmlspecialchars($currentConfig['wxis_host'] ?? '127.0.0.1'); ?>" style="width: 100%; max-width: 400px; padding: 8px;">
                    </div>
                    <div style="margin-bottom: 15px;">
                        <label style="display: block; font-weight: bold;"><?php echo $msgstr['api_root_path'] ?? 'API Root Physical Path'; ?></label>
                        <input type="text" name="api_root_path" value="<?php echo htmlspecialchars($currentConfig['api_root_path'] ?? str_replace('\\', '/', $apiRootPath)); ?>" style="width: 100%; padding: 8px;">
                    </div>
                    <button type="submit" class="bt bt-blue"><i class="fas fa-save"></i> <?php echo $msgstr['api_save_general'] ?? 'Save General Settings'; ?></button>
                </form>
            </fieldset>

            <!-- ACCESS KEYS TAB -->
            <fieldset style="border: 1px solid #ccc; padding: 15px; margin-bottom: 20px; border-radius: 5px; background-color: #f9f9f9;">
                <legend style="font-weight: bold; padding: 0 5px;"><?php echo $msgstr['api_access_keys'] ?? 'API Access Keys'; ?></legend>
                <div style="background: #fff; padding: 15px; border: 1px solid #ddd; border-radius: 5px; margin-bottom: 20px;">
                    <form method="POST" style="display: flex; gap: 15px; align-items: flex-end;">
                        <input type="hidden" name="action" value="generate_key">
                        <div style="flex-grow: 1;">
                            <label style="display: block; font-weight: bold; font-size: 13px;"><?php echo $msgstr['api_client_name'] ?? 'Client / App Name'; ?></label>
                            <input type="text" name="client_name" required style="width: 100%; padding: 8px;">
                        </div>
                        <div>
                            <label style="display: block; font-weight: bold; font-size: 13px;"><?php echo $msgstr['api_scope'] ?? 'Scope'; ?></label>
                            <select name="scope" style="padding: 8px; width: 150px;">
                                <option value="read"><?php echo $msgstr['api_scope_read'] ?? 'Read Only'; ?></option>
                                <option value="write"><?php echo $msgstr['api_scope_write'] ?? 'Read & Write'; ?></option>
                            </select>
                        </div>
                        <button type="submit" class="bt bt-green"><i class="fas fa-key"></i> <?php echo $msgstr['api_generate_key'] ?? 'Generate Key'; ?></button>
                    </form>
                </div>

                <!-- KEYS TABLE -->
                <table style="width: 100%; border-collapse: collapse; text-align: left; background: #fff;">
                    <thead>
                        <tr style="background-color: #e2e8f0; border-bottom: 2px solid #cbd5e1;">
                            <th style="padding: 10px;"><?php echo $msgstr['api_client_name'] ?? 'Client Name'; ?></th>
                            <th style="padding: 10px;"><?php echo $msgstr['api_created_at'] ?? 'Created At'; ?></th>
                            <th style="padding: 10px;"><?php echo $msgstr['api_scope'] ?? 'Scope'; ?></th>
                            <th style="padding: 10px;"><?php echo $msgstr['api_status'] ?? 'Status'; ?></th>
                            <th style="padding: 10px; width: 80px; text-align: center;"><?php echo $msgstr['api_actions'] ?? 'Actions'; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (empty($registry)): ?>
                            <tr>
                                <td colspan="5" style="padding: 15px; text-align: center; color: #64748b;"><?php echo $msgstr['api_no_keys'] ?? 'No API keys generated yet.'; ?></td>
                            </tr>
                        <?php else: ?>
                            <?php foreach ($registry as $hash => $data): ?>
                                <tr style="border-bottom: 1px solid #ddd;">
                                    <td style="padding: 10px;"><strong><?php echo htmlspecialchars($data['client_name']); ?></strong></td>
                                    <td style="padding: 10px;"><?php echo htmlspecialchars($data['created_at']); ?></td>
                                    <td style="padding: 10px;">
                                        <span style="background: #e2e8f0; padding: 3px 8px; border-radius: 10px; font-size: 12px;">
                                            <?php echo htmlspecialchars($data['scope'] === 'read' ? ($msgstr['api_scope_read'] ?? 'Read Only') : ($msgstr['api_scope_write'] ?? 'Read & Write')); ?>
                                        </span>
                                    </td>
                                    <td style="padding: 10px;">
                                        <span style="color: green; font-weight: bold;"><?php echo $msgstr['api_active'] ?? 'Active'; ?></span>
                                    </td>
                                    <td style="padding: 10px; text-align: center;">
                                        <form method="POST" style="margin: 0;" onsubmit="return confirm('<?php echo addslashes($msgstr['api_revoke_confirm'] ?? 'Are you sure you want to revoke this key? Any application using it will immediately lose access.'); ?>');">
                                            <input type="hidden" name="action" value="delete_key">
                                            <input type="hidden" name="key_hash" value="<?php echo htmlspecialchars($hash); ?>">
                                            <button type="submit" class="bt bt-red" title="<?php echo $msgstr['api_revoke_key'] ?? 'Revoke Key'; ?>" style="padding: 4px 8px;">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </fieldset>

            <!-- DATABASES AND MAPPING UNIFIED TAB -->
            <fieldset style="border: 1px solid #ccc; padding: 15px; margin-bottom: 20px; border-radius: 5px;">
                <legend style="font-weight: bold; padding: 0 5px;"><?php echo $msgstr['api_db_exposure'] ?? 'Database Exposure & Mappings'; ?></legend>
                <p style="color: #555; margin-bottom: 15px;"><?php echo $msgstr['api_db_exposure_desc'] ?? 'Enable databases, set access levels, and map CISIS indexes. Click a database to expand its configuration.'; ?></p>

                <form method="POST">
                    <input type="hidden" name="action" value="save_db_config">

                    <?php
                    $masterBases = file_exists($db_path . 'bases.dat') ? file($db_path . 'bases.dat', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) : [];

                    foreach ($masterBases as $line) {
                        list($dbCode, $humanName) = explode('|', trim($line));
                        $dbCode = str_replace(['.def', '.par'], '', $dbCode);
                        if (in_array(substr($humanName, 0, 3), ['Acq', 'Sys']) || substr($humanName, 0, 4) === 'Circ') continue;

                        $isActive = isset($databasesConfig[$dbCode]);
                        $hasCheckedClass = $isActive ? 'has-checked' : '';
                        $currentAccess = $databasesConfig[$dbCode]['access'] ?? 'restricted';
                        $currentDesc = $databasesConfig[$dbCode]['description'] ?? $humanName;
                        $currentMapping = $searchConfig[$dbCode] ?? [];
                    ?>
                        <div class="abcd-accordion-item <?php echo $hasCheckedClass; ?>" id="acc-db-<?php echo htmlspecialchars($dbCode); ?>">
                            <div class="abcd-accordion-header" onclick="toggleAccordion('acc-db-<?php echo htmlspecialchars($dbCode); ?>')">
                                <h4>
                                    <input type="checkbox" name="enable_db[]" value="<?php echo htmlspecialchars($dbCode); ?>" <?php echo $isActive ? 'checked' : ''; ?> onclick="event.stopPropagation(); checkAccordionHighlight(this, 'acc-db-<?php echo htmlspecialchars($dbCode); ?>')">
                                    <i class="fas fa-database"></i> <?php echo htmlspecialchars($dbCode); ?> - <small><?php echo htmlspecialchars($humanName); ?></small>
                                </h4>
                                <span><i class="fas fa-chevron-down"></i></span>
                            </div>

                            <div class="abcd-accordion-content">
                                <?php
                                $detectedEnv = detectCisisEnvironment($db_path, $dbCode);
                                $currentCisis = $databasesConfig[$dbCode]['cisis_version'] ?? $detectedEnv['cisis_version'];
                                $currentEncoding = $databasesConfig[$dbCode]['source_encoding'] ?? $detectedEnv['source_encoding'];
                                ?>

                                <div style="display: flex; gap: 15px; margin-bottom: 15px; flex-wrap: wrap;">
                                    <div style="flex-grow: 1; min-width: 200px;">
                                        <label style="font-weight:bold;"><?php echo $msgstr['api_db_desc'] ?? 'API Description'; ?></label>
                                        <input type="text" name="db_desc[<?php echo htmlspecialchars($dbCode); ?>]" value="<?php echo htmlspecialchars($currentDesc); ?>" style="width: 100%; padding: 5px; border: 1px solid #ccc; border-radius: 4px;">
                                    </div>
                                    <div style="width: 180px;">
                                        <label style="font-weight:bold;"><?php echo $msgstr['api_access_level'] ?? 'Access Level'; ?></label>
                                        <select name="access_level[<?php echo htmlspecialchars($dbCode); ?>]" style="width: 100%; padding: 6px; border: 1px solid #ccc; border-radius: 4px;">
                                            <option value="public" <?php echo $currentAccess === 'public' ? 'selected' : ''; ?>><?php echo $msgstr['api_public'] ?? 'Public (No Key)'; ?></option>
                                            <option value="restricted" <?php echo $currentAccess === 'restricted' ? 'selected' : ''; ?>><?php echo $msgstr['api_restricted'] ?? 'Restricted (Requires Key)'; ?></option>
                                        </select>
                                    </div>
                                    <div style="width: 140px;">
                                        <label style="font-weight:bold;" title="Detected from dr_path.def"><?php echo $msgstr['api_cisis_env'] ?? 'CISIS Env'; ?> <i class="fas fa-magic" style="color:#aaa; font-size:10px;"></i></label>
                                        <select name="cisis_version[<?php echo htmlspecialchars($dbCode); ?>]" style="width: 100%; padding: 6px; border: 1px solid #ccc; border-radius: 4px;">
                                            <?php
                                            $commonVersions = ['ansi/', 'utf8/', 'utf8/bigisis/', 'ansi/bigisis/'];
                                            if (!in_array($currentCisis, $commonVersions)) {
                                                echo "<option value=\"" . htmlspecialchars($currentCisis) . "\" selected>" . htmlspecialchars($currentCisis) . "</option>";
                                            }
                                            foreach ($commonVersions as $ver) {
                                                $selected = ($currentCisis === $ver) ? 'selected' : '';
                                                echo "<option value=\"{$ver}\" {$selected}>{$ver}</option>";
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div style="width: 120px;">
                                        <label style="font-weight:bold;"><?php echo $msgstr['api_encoding'] ?? 'Encoding'; ?></label>
                                        <select name="source_encoding[<?php echo htmlspecialchars($dbCode); ?>]" style="width: 100%; padding: 6px; border: 1px solid #ccc; border-radius: 4px;">
                                            <option value="ISO-8859-1" <?php echo $currentEncoding === 'ISO-8859-1' ? 'selected' : ''; ?>>ISO-8859-1</option>
                                            <option value="UTF-8" <?php echo $currentEncoding === 'UTF-8' ? 'selected' : ''; ?>>UTF-8</option>
                                        </select>
                                    </div>
                                </div>

                                <h5><i class="fas fa-search"></i> <?php echo $msgstr['api_search_mappings'] ?? 'Search Index Mappings'; ?></h5>
                                <table class="table striped mapping-table" style="width: 100%; margin-bottom: 10px;">
                                    <thead>
                                        <tr>
                                            <th><?php echo $msgstr['api_param_name'] ?? 'API Parameter (e.g., author)'; ?></th>
                                            <th><?php echo $msgstr['api_cisis_prefix'] ?? 'CISIS Prefix (e.g., AU_)'; ?></th>
                                            <th style="width: 120px; text-align: center;"><?php echo $msgstr['api_actions'] ?? 'Actions'; ?></th>
                                        </tr>
                                    </thead>
                                    <tbody id="mapping_body_<?php echo htmlspecialchars($dbCode); ?>">
                                        <?php if (!empty($currentMapping)): ?>
                                            <?php foreach ($currentMapping as $apiParam => $cisisPrefix): ?>
                                                <tr>
                                                    <td><input type="text" name="mapping[<?php echo htmlspecialchars($dbCode); ?>][api_param][]" value="<?php echo htmlspecialchars($apiParam); ?>" style="width: 95%; padding: 5px;"></td>
                                                    <td><input type="text" name="mapping[<?php echo htmlspecialchars($dbCode); ?>][cisis_prefix][]" value="<?php echo htmlspecialchars($cisisPrefix); ?>" style="width: 95%; padding: 5px;"></td>
                                                    <td style="text-align: center;">
                                                        <button type="button" class="bt bt-gray" onclick="duplicateRow(this)"><i class="far fa-copy"></i></button>
                                                        <button type="button" class="bt bt-red" onclick="deleteRow(this)"><i class="fas fa-trash-alt"></i></button>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <!-- Initial Empty Row -->
                                            <tr>
                                                <td><input type="text" name="mapping[<?php echo htmlspecialchars($dbCode); ?>][api_param][]" placeholder="<?php echo $msgstr['api_new_param'] ?? 'New parameter...'; ?>" style="width: 95%; padding: 5px;"></td>
                                                <td><input type="text" name="mapping[<?php echo htmlspecialchars($dbCode); ?>][cisis_prefix][]" placeholder="<?php echo $msgstr['api_new_prefix'] ?? 'Prefix...'; ?>" style="width: 95%; padding: 5px;"></td>
                                                <td style="text-align: center;">
                                                    <button type="button" class="bt bt-gray" onclick="duplicateRow(this)"><i class="far fa-copy"></i></button>
                                                    <button type="button" class="bt bt-red" onclick="deleteRow(this)"><i class="fas fa-trash-alt"></i></button>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                                <button type="button" class="bt bt-gray" onclick="addMappingRow('mapping_body_<?php echo htmlspecialchars($dbCode); ?>', '<?php echo htmlspecialchars($dbCode); ?>')">
                                    <i class="fas fa-plus"></i> <?php echo $msgstr['api_add_mapping'] ?? 'Add Mapping Row'; ?>
                                </button>
                            </div>
                        </div>
                    <?php } ?>

                    <div style="margin-top: 20px;">
                        <button type="submit" class="bt bt-blue"><i class="fas fa-save"></i> <?php echo $msgstr['api_save_all_db'] ?? 'Save All Database Configurations'; ?></button>
                    </div>
                </form>
            </fieldset>

        </div>
    </div>

    <!-- UI Scripts -->
    <script>
        function toggleAccordion(id) {
            const item = document.getElementById(id);
            if (item) {
                item.classList.toggle('open');
            }
        }

        function checkAccordionHighlight(checkbox, accordionId) {
            const item = document.getElementById(accordionId);
            if (checkbox.checked) {
                item.classList.add('has-checked');
            } else {
                item.classList.remove('has-checked');
            }
        }

        function addMappingRow(tbodyId, dbKey) {
            const tbody = document.getElementById(tbodyId);
            const tr = document.createElement("tr");
            tr.innerHTML = `
                <td><input type="text" name="mapping[${dbKey}][api_param][]" placeholder="<?php echo $msgstr['api_new_param'] ?? 'New parameter...'; ?>" style="width: 95%; padding: 5px;"></td>
                <td><input type="text" name="mapping[${dbKey}][cisis_prefix][]" placeholder="<?php echo $msgstr['api_new_prefix'] ?? 'Prefix...'; ?>" style="width: 95%; padding: 5px;"></td>
                <td style="text-align: center;">
                    <button type="button" class="bt bt-gray" onclick="duplicateRow(this)"><i class="far fa-copy"></i></button>
                    <button type="button" class="bt bt-red" onclick="deleteRow(this)"><i class="fas fa-trash-alt"></i></button>
                </td>
            `;
            tbody.appendChild(tr);
        }

        function duplicateRow(btn) {
            const row = btn.closest("tr");
            const clone = row.cloneNode(true);
            row.parentNode.insertBefore(clone, row.nextSibling);
        }

        function deleteRow(btn) {
            const row = btn.closest("tr");
            row.remove();
        }
    </script>

    <?php include("../common/footer.php"); ?>
</body>

</html>